name: Build IPA

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: macOS-latest

    steps:
    - uses: actions/checkout@v3

    - uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: latest-stable

#    - name: Install CocoaPods
#      run: sudo gem install cocoapods

#    - name: Install Dependencies
#      run: |
#        pod install

    - name: Build and Archive
      run: |
        xcodebuild -showsdks
        xcodebuild archive \
        -project klassenarbeits-text-editor.xcodeproj \
        -scheme klassenarbeits-text-editor \
        -archivePath klassenarbeits-text-editor.xcarchive \
        -sdk iphoneos \
        -configuration Release \
        -codeSigningIdentity "" \
        -codeSigningRequired NO

    - name: Export Archive
      run: |
        xcodebuild -exportArchive \
        -archivePath klassenarbeits-text-editor.xcarchive \
        -exportPath klassenarbeits-text-editor \
        -exportOptionsPlist exportOptions.plist \
        -developmentTeam "" \
        -codeSigningIdentity "" \
        -codeSigningRequired NO

    - name: Compress IPA
      run: |
        cd klassenarbeits-text-editor
        zip -r -X klassenarbeits-text-editor.ipa Payload
